### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by andra1133** [csprajeeth/rk-bot#1]
Does it bot still work?

I already tried it but it looks like NK bot look very similar
if it still work pls give any guide or anything for RK I use guide from NK bot but it doesn't work

**Comment by andra1133** [comment]
I got this error

```
Traceback (most recent call last):
  File "C:\Users\7\Downloads\rk-bot-master\rktest.py", line 14, in <module>
    char = Character(username, password, br, sys.stdout)
  File "C:\Users\7\Downloads\rk-bot-master\character.py", line 50, in __init__
    self.home = Home(self)
  File "C:\Users\7\Downloads\rk-bot-master\home.py", line 21, in __init__
    self.update_inventory()
  File "C:\Users\7\Downloads\rk-bot-master\home.py", line 50, in update_inventory
    self.money = soup.find('div', {'id' : 'Item10'}).text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by csprajeeth** [comment]
Hi,

This bot is very old ~4 years. It might need updating because HTML
structure of the game has changed a lot since then. However when it worked,
I used it to make 14000 gold. Very effective.

**Comment by andra1133** [comment]
thanks for the reply. 
hmm, I see, the bot for nk worked pretty well tho. well if u ever plan to update it let me know pls 

thanks
